import React from "react";

import { Geist, Geist_Mono } from "next/font/google";

import { ConfigProvider } from "antd";
import { NextIntlClientProvider } from "next-intl";

import type { Metadata } from "next";

import "../globals.css";
import { Header } from "@/src/widgets/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-auto max-w-[1440px] p-4">
      <div className="flex w-full justify-center rounded-lg shadow-2xl">
        <Header />
        <main className="w-full px-15 py-6">
          <ConfigProvider>
            <NextIntlClientProvider>{children}</NextIntlClientProvider>
          </ConfigProvider>
        </main>
      </div>
    </div>
  );
}
